import assert from 'node:assert/strict';
import { JSDOM } from 'jsdom';
import { build } from 'esbuild';
import { pathToFileURL } from 'node:url';
import path from 'node:path';
import { readFile } from 'node:fs/promises';
import {season3Players} from '../src/season3-roster.js';

const dom = new JSDOM('<!doctype html><html><body></body></html>', {url:'http://localhost:4173/',pretendToBeVisual:true});
for (const key of ['window','document','HTMLElement','Node','localStorage','MutationObserver']) Object.defineProperty(globalThis,key,{value:dom.window[key],configurable:true});
Object.defineProperty(globalThis,'navigator',{value:dom.window.navigator,configurable:true});
window.scrollTo=()=>{};
window.YT={Player:class{destroy(){}}};
window.matchMedia=()=>({matches:true,addEventListener(){},removeEventListener(){},addListener(){},removeListener(){}});
globalThis.requestAnimationFrame=window.requestAnimationFrame.bind(window);
globalThis.cancelAnimationFrame=window.cancelAnimationFrame.bind(window);
globalThis.getComputedStyle=window.getComputedStyle.bind(window);
globalThis.Element=window.Element;
globalThis.SVGElement=window.SVGElement;
globalThis.IntersectionObserver=class {observe(){} unobserve(){} disconnect(){}};
globalThis.fetch=async()=>({ok:false});
window.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','')};
window.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open')};
const React=await import('react');
const {render,screen,fireEvent,cleanup,waitFor}=await import('@testing-library/react');
const outfile=path.resolve('node_modules/.cache/wcl-tests.mjs');
await build({entryPoints:['src/League.jsx'],outfile,bundle:true,format:'esm',platform:'node',jsx:'automatic',external:['react','react-dom','react/*','react-dom/*'],loader:{'.css':'empty'}});
const {League}=await import(pathToFileURL(outfile).href);
const data=JSON.parse(await readFile('src/data/wcl.json','utf8'));
const known=new Set(['india','pakistan','south-africa','australia','england','west-indies','bangladesh']);
function page(path){cleanup();window.history.replaceState({},'',path);return render(React.createElement(League))}
async function story(label){for(let i=0;i<14;i++){const current=document.querySelector('.story-scene').getAttribute('aria-label');if(current.endsWith(': '+label))return;fireEvent.click(screen.getByRole('button',{name:'Next story'}));await waitFor(()=>assert.notEqual(document.querySelector('.story-scene').getAttribute('aria-label'),current))}throw Error('Story not found: '+label)}
try {
  assert.equal(new Set(data.players.map(p=>p.id)).size,data.players.length);
  assert.equal(data.matches.length,36);
  assert(data.matches.every(m=>m.teams.length===2&&m.teams.every(t=>known.has(t))));
  assert(data.videos.every(v=>/^[\w-]{11}$/.test(v.id)&&v.source.startsWith('https://wclcricket.com/')));
  console.log('PASS imported records have unique IDs and valid relationships');
  page('/');
  assert(screen.getByRole('heading',{level:1,name:'LEGENDS. LIVE ON.'}));
  await story('India × Pakistan');
  assert(await screen.findByRole('heading',{level:1,name:'OLD RIVALRIES. NEW CHAPTERS.'}));
  await story('England × Australia');
  assert(await screen.findByRole('heading',{level:1,name:'HISTORY RUNS DEEP.'}));
  await story('India × Pakistan');
  assert(await screen.findByRole('heading',{level:1,name:'OLD RIVALRIES. NEW CHAPTERS.'}));
  console.log('PASS sports hero feature navigation');
  assert.equal(document.querySelectorAll('.home-player-grid .player-card').length,8);
  assert(!screen.queryByRole('textbox',{name:'Find players on homepage'}));
  fireEvent.click(screen.getByRole('button',{name:'Show India players'}));
  assert.equal(document.querySelectorAll('.home-player-grid .player-card').length,8);
  fireEvent.click(screen.getByRole('button',{name:/Shahid Afridi/}));
  assert(document.querySelector('.spotlight-bio h2').textContent.includes('Shahid Afridi'));
  fireEvent.change(document.querySelector('.mc-home select[aria-label="Season"]'),{target:{value:'3'}});
   assert.equal(document.querySelectorAll('.mc-home .mc-fixture').length,2);
   assert.equal(document.querySelectorAll('.mc-home .ms-stage').length,1);
  console.log('PASS homepage team browsing, spotlight selection and season widget');
  page('/players');
  fireEvent.click(document.getElementById('team-toggle-india'));
  assert.equal(document.querySelectorAll('#roster-india .player-card').length,14);
  fireEvent.click(screen.getByRole('link',{name:/Yuvraj Singh/i}));
  assert.equal(window.location.pathname,'/players/india-yuvraj-singh');
  assert(screen.getByRole('heading',{level:1,name:/Yuvraj Singh/i}));
  console.log('PASS team expansion opens correct player profile');
  page('/matches');
   assert.equal(document.querySelectorAll('.mc-fixture').length,24);
  fireEvent.change(screen.getByLabelText('Season'),{target:{value:'2'}});
  assert.equal(document.querySelectorAll('.mc-fixture').length,18);
  fireEvent.change(screen.getByLabelText('Team'),{target:{value:'india'}});
  assert.equal(document.querySelectorAll('.mc-fixture').length,data.matches.filter(m=>m.season===2&&m.teams.includes('india')).length);
  console.log('PASS season and team filters preserve archive semantics');
  page('/teams/india');
  fireEvent.click(screen.getByRole('tab',{name:'Players'}));
  assert.equal(document.querySelectorAll('.player-card').length,season3Players.filter(p=>p.team==='india').length);
  fireEvent.click(screen.getByRole('button',{name:'Make this my team'}));
  assert.equal(JSON.parse(localStorage.getItem('wcl-fan')).team,'india');
  page('/fan-zone');
  assert.equal(screen.getByRole('button',{name:'India'}).getAttribute('aria-pressed'),'true');
  console.log('PASS team tab and favourite persist across routes');
  const v=data.videos[0];page(`/watch/${v.id}`);
  assert.equal(new URL(document.querySelector('iframe').src).pathname,`/embed/${v.id}`);
  fireEvent.click(screen.getByRole('button',{name:'Save video'}));
  page('/fan-zone');assert.equal(document.querySelectorAll('.video-card').length,1);
  page('/privacy');assert(screen.getByRole('heading',{level:1,name:'Privacy Policy'}));
  page('/cookies');fireEvent.click(screen.getByRole('button',{name:'Clear my WCL preferences'}));assert.equal(localStorage.getItem('wcl-fan'),null);
  console.log('PASS video save, collection and privacy deletion');
  page('/standings');assert.equal(window.location.pathname,'/matches');
  page('/stats');assert.equal(window.location.pathname,'/players');
  page('/unknown');assert(screen.getByRole('heading',{name:'That page is out of play.'}));
  console.log('PASS removed-route redirects and unknown-route recovery');
} finally {cleanup();dom.window.close();}
