import {useId} from 'react';
export function ContentControls({collection,value,onChange,readOnly=false}){
 const prefix=useId();let p;try{p=JSON.parse(value)}catch{return null}
 const set=(key,v)=>onChange(JSON.stringify({...p,[key]:v},null,2));
 const field=(key,label,type='text',options)=> <label key={key} className="admin-visual-field" htmlFor={prefix+key}><span>{label}</span>{options?<select id={prefix+key} value={p[key]??''} disabled={readOnly} onChange={e=>set(key,e.target.value)}>{options.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select>:<input id={prefix+key} type={type} disabled={readOnly} value={p[key]??''} onChange={e=>set(key,type==='number'?Number(e.target.value):e.target.value)}/>}</label>;
 const check=(key,label,defaultValue=true)=><label className="admin-check" key={key}><input type="checkbox" disabled={readOnly} checked={p[key]??defaultValue} onChange={e=>set(key,e.target.checked)}/>{label}</label>;
 const verify=[['pending','Awaiting verification'],['verified','Verified']];
 return <div className="content-visual-controls">
 {['hero','news','brands','players'].includes(collection)&&(p.image||p.thumbnail)&&<img className="content-preview-image" src={p.image||p.thumbnail} alt="Current record preview"/>}
 {collection==='hero'&&<>{check('visible','Show this story in the hero')}{field('order','Story order','number')}{field('videoId','YouTube video ID · explicit play only')}{field('image','Story image URL')}{field('alt','Image description')}{field('supportingCopy','Optional supporting paragraph')}{field('chapter','Optional chapter line')}{field('role','Leadership role')}{field('source','Biography source · HTTPS')}<p>Manual dots, keyboard and swipe stay available. A video never starts before the visitor chooses Play.</p></>}
 {collection==='players'&&<>{field('portraitReviewStatus','Portrait review',null,[['original','Use original photograph'],['pending','Pending review · keep original'],['approved','Approved campaign adaptation'],['held','Hold replacement · keep original']])}<div className="portrait-source-preview">{p.headshot&&<figure><img src={p.headshot} alt={'Original: '+p.name}/><figcaption>Original identity source</figcaption></figure>}{p.portraitVariants?.profile&&<figure><img src={p.portraitVariants.profile} alt={'Campaign candidate: '+p.name}/><figcaption>Campaign adaptation</figcaption></figure>}</div>{['card','profile'].map(key=><label key={key} className="admin-visual-field"><span>{key} image URL</span><input disabled={readOnly} value={p.portraitVariants?.[key]||''} onChange={e=>set('portraitVariants',{...p.portraitVariants,[key]:e.target.value})}/></label>)}<p>Compare face, skin tone, expression and team kit before approving. Source images remain unchanged. Never use another player’s portrait.</p></>}
 {collection==='fixtures'&&<>{field('status','Match status',null,[['Scheduled','Scheduled'],['Live','Live'],['Completed','Completed'],['Postponed','Postponed'],['Cancelled','Cancelled']])}{field('verificationStatus','Score/result verification',null,verify)}{field('result','Verified result summary')}{field('startsAt','Start · ISO date with timezone')}{field('venue','Venue allocation')}<p>Hero priority: verified live match, next scheduled fixture, latest verified result. No result is inferred from archive schedules.</p></>}
 {collection==='tickets'&&<>{field('matchId','Fixture ID')}{field('availability','Availability',null,[['coming-soon','Coming soon'],['on-sale','On sale'],['sold-out','Sold out']])}{field('verificationStatus','Ticketing verification',null,verify)}{field('provider','Authorized ticket provider')}{field('bookingUrl','Verified booking URL · HTTPS')}{field('venue','Confirmed stadium')}{field('priceLabel','Verified pricing / currency')}<p>An on-sale record requires verified status, a named provider and an HTTPS booking URL.</p></>}
 {collection==='brands'&&<>{field('name','Brand name')}{field('image','Original logo URL')}{field('association','Season association')}{field('order','Collection order','number')}<p>Keep original colours and proportions. A historical association is not a Season 3 sponsorship claim.</p></>}
 {collection==='news'&&<>{field('thumbnail','Article thumbnail URL')}{field('imageAlt','Image description')}{field('imageCredit','Publisher / photographer credit')}{check('featured','Feature this story',false)}</>}
 {collection==='experience'&&<>{check('motionEnabled','Enable decorative motion')}{check('brandMotion','Allow slow-moving brand rows')}{field('brandDuration','Brand row duration · 80–180 seconds','number')}{field('revealDuration','Reveal duration · 0.15–0.6 seconds','number')}<p>Visitor reduced-motion preferences always override these settings.</p></>}
 </div>
}
export function contentTemplate(collection,order=0){
 const base={id:'new-record',order};
 if(collection==='hero')return {...base,label:'New story',title:'NEW CHAPTER.',line:'LEGENDS LIVE ON.',tag:'WCL / SEASON 3',copy:'Add approved story copy.',image:'/assets/season3-ensemble-2026.webp',alt:'Season 3 campaign',action:'Explore Season 3',to:'/season',secondary:'Match centre',secondaryTo:'/matches',facts:[],visible:false};
 if(collection==='tickets')return {...base,label:'Match ticket availability',matchId:'choose-fixture-id',availability:'coming-soon',verificationStatus:'pending'};
 if(collection==='experience')return {id:'motion',motionEnabled:true,brandMotion:true,brandDuration:110,revealDuration:.35};
 if(collection==='players')return {...base,name:'New player',team:'india',role:'Player',headshot:'',portraitReviewStatus:'pending'};
 return {...base,title:'New title'};
}
