import {usePageCopy,RichCopy} from './cms/SiteContent.jsx';
import {useState} from 'react';
import {Link, NavLink} from 'react-router-dom';
import {ArrowUpRight} from '@phosphor-icons/react';

const Email = () => <a href="mailto:info@wclcricket.com">info@wclcricket.com</a>;
const External = ({href, children}) => <a href={href} target="_blank" rel="noreferrer">{children} <ArrowUpRight size={12}/></a>;
function Part({id, title, children}) { return <section id={id} className="policy-part"><h2>{title}</h2>{children}</section>; }
function Preferences() {
  const [message, setMessage] = useState('');
  return <><button className="btn" onClick={() => {try {localStorage.removeItem('wcl-fan'); sessionStorage.removeItem('wcl-opening-seen'); setMessage('Your saved team, videos and opening-sequence preference have been cleared from this device.');} catch {setMessage('Storage is blocked in this browser. You can remove this website’s data in your browser settings.');}}}>Clear my WCL preferences</button><p role="status">{message}</p></>;
}

export function PolicyPage({kind = 'privacy'}) {
  const page=usePageCopy('/'+kind);
  const titles = {privacy: 'Privacy Policy', cookies: 'Cookies & storage', terms: 'Terms of use'};
  const fallbackSections = kind === 'privacy' ? [['scope','Who this notice is for'],['information','Information we handle'],['purposes','How and why it is used'],['sharing','Services and sharing'],['retention','Keeping information safe'],['rights','Your choices and rights'],['updates','Contact and updates']] : kind === 'cookies' ? [['storage','What this website stores'],['services','Media and external services'],['controls','Your browser controls']] : [['using','Using the website'],['content','Content and ownership'],['events','Matches, tickets and third parties'],['enquiries','Enquiries and responsible use'],['rights','Your rights and changes']];
  const sections=page?.sections?.length?page.sections.map(s=>[s.id,s.title]):fallbackSections;
  return <>
    <div className="page-title"><div className="wrap"><p className="kicker">{page?.tag||"PRIVACY & POLICIES"}</p><h1>{page?.title||titles[kind]}</h1><p>{page?.intro||"Clear information. Considered choices. Your WCL experience."}</p></div></div>
    <div className="wrap policy-navigation"><nav aria-label="Policies"><NavLink to="/privacy">Privacy</NavLink><NavLink to="/cookies">Cookies & storage</NavLink><NavLink to="/terms">Terms of use</NavLink></nav><span>Last updated · {page?.updatedAt?new Date(page.updatedAt).toLocaleDateString("en-GB",{day:"numeric",month:"long",year:"numeric",timeZone:"UTC"}):"11 September 2026"}</span></div>
    <div className="wrap policy-layout"><aside><p className="kicker">ON THIS PAGE</p><nav aria-label="On this page">{sections.map(([id,title]) => <a key={id} href={`#${id}`}>{title}</a>)}</nav><Link className="policy-help" to="/contact">Need to speak to us? <ArrowUpRight size={16}/></Link></aside>
      <article className="policy-copy">{page?.sections?.map(s=><Part key={s.id} id={s.id} title={s.title}><RichCopy text={s.body}/>{kind==="cookies"&&s.id==="controls"&&<Preferences/>}</Part>)}
      {!page?.sections?.length && kind === 'privacy' && <>
        <Part id="scope" title="Who this notice is for"><p>This notice explains how World Championship of Legends (WCL) handles information in connection with this public website and enquiries sent to WCL. For website privacy questions, contact <Email/>.</p><p>It covers browsing, saved website preferences and the contact form. Ticket sellers, external social platforms and any separate accreditation or staff application have their own notices. Read the notice shown by that service before submitting information there.</p></Part>
        <Part id="information" title="Information we handle"><ul><li><strong>Enquiries:</strong> the name, email address, enquiry topic and message you submit, your acknowledgement of this notice, a submission reference and any subsequent correspondence.</li><li><strong>Website preferences:</strong> your chosen team and saved video identifiers are stored in your browser when you choose those features. The website does not create a fan account from these choices.</li><li><strong>Technical information:</strong> hosting and security services may process your IP address, browser and device information, request times, requested pages and security signals to deliver and protect the service.</li></ul><p>Please only provide information needed for your enquiry. Do not send card details, passwords, passport copies, medical information or confidential information about another person through this form.</p></Part>
        <Part id="purposes" title="How and why it is used"><p>Enquiry information is used to understand your request, direct it to the appropriate WCL team and respond. Technical information supports website delivery, fault diagnosis and abuse prevention. Your browser preferences provide the team and video-saving features you select.</p><p>Where a law requires a lawful basis, responding to an ordinary enquiry and keeping the website secure may rely on legitimate interests; steps you request before entering an agreement may rely on that purpose; and some records may be needed to meet legal obligations. If consent is needed for an additional purpose, it must be requested separately. A privacy acknowledgement is not marketing consent.</p><p>This contact form does not subscribe you to a mailing list, take payments or make automated decisions about you with legal or similarly significant effects.</p></Part>
        <Part id="sharing" title="Services and sharing"><p>Information may be accessed by WCL personnel who need it to handle your request and service providers supporting the website. The contact service uses Vercel for hosting, Resend for email delivery and Cloudflare Turnstile for spam prevention when online enquiries are enabled. Messages are addressed to WCL’s enquiry mailbox, not published on the website.</p><p>These providers may process information in countries other than your own. Applicable protections and transfer arrangements depend on WCL’s provider contracts and deployment settings. Information may also need to be disclosed where required by law or to protect legitimate legal rights.</p><p>YouTube supplies video thumbnails and players. Maps and social links connect to their respective providers. Those providers receive technical information when their content loads or you visit their services. See <Link to="/cookies">Cookies & storage</Link> for how these features work.</p><p>Provider notices: <External href="https://vercel.com/legal/privacy-policy">Vercel</External>, <External href="https://resend.com/legal/privacy-policy">Resend</External>, <External href="https://www.cloudflare.com/privacypolicy/">Cloudflare</External> and <External href="https://policies.google.com/privacy">Google / YouTube</External>.</p></Part>
        <Part id="retention" title="Keeping information safe"><p>The form does not create a separate contact database in this website. Enquiries pass through the delivery service to WCL’s mailbox. Mailbox correspondence and delivery or security records may remain after submission.</p><p>Retention depends on the purpose and progress of your enquiry, any continuing relationship, applicable legal requirements and the need to resolve disputes. Hosting and delivery logs also follow the relevant service settings. You can ask about the records held for your enquiry or request deletion using <Email/>.</p><p>Access controls, server-side validation and security checks help protect the service. No internet transmission or storage system is completely secure. Do not use the form for sensitive or urgent security information. Browser preferences remain until you clear them or your browser removes site data.</p></Part>
        <Part id="rights" title="Your choices and rights"><p>Depending on the law that applies to you, you may have rights to access, correct, delete or receive a copy of your personal information, restrict processing, object to certain uses or withdraw consent where processing relies on it. These rights can be subject to legal exceptions.</p><p>Send a request to <Email/> or choose “Privacy request” in the <Link to="/contact">contact form</Link>. Explain what you would like us to do; we may need proportionate information to verify your identity. Do not attach identity documents to an initial request. You may also raise a concern with the data-protection authority relevant to your location.</p><p>You can remove saved preferences using <Link to="/cookies#controls">browser storage controls</Link>. This does not remove an enquiry already sent to WCL. If a child has provided information without appropriate permission, a parent or guardian can contact us to ask for it to be reviewed.</p></Part>
        <Part id="updates" title="Contact and updates"><p>Questions about this notice or your information can be sent to <Email/>. The date above identifies the current version. Material changes to how information is used should be reflected here and communicated separately where required.</p></Part>
      </>}
      {!page?.sections?.length && kind === 'cookies' && <>
        <Part id="storage" title="What this website stores"><p>Cookies and browser storage are small records used by websites. The public WCL website uses the following first-party browser preferences; these are not a mailing-list subscription or a fan account.</p><div className="policy-storage"><div><strong>wcl-fan</strong><span>Local storage · your selected team and saved video IDs. Remains on this device until cleared.</span></div><div><strong>wcl-opening-seen</strong><span>Session storage · remembers whether the opening sequence was shown. Cleared when the browser session ends.</span></div></div><p>The public website does not currently include an advertising pixel or an audience-analytics script in its application code. Hosting infrastructure can still keep request and security logs. Separate staff portals may use a necessary sign-in session cookie; their access and application notices apply separately.</p></Part>
        <Part id="services" title="Media and external services"><p>YouTube thumbnails load on pages that display them. Opening a WCL watch page loads a YouTube player, which can make requests to Google and use its own storage. Playback and sign-in preferences are controlled by YouTube.</p><p>Interactive maps connect to their map provider when loaded. Instagram cards open the original post on Instagram when selected. These services have their own cookies, privacy notices and controls. Closing an embedded player does not automatically delete storage already set by that provider.</p><p>When the contact service is enabled, Cloudflare Turnstile processes security signals to check whether a submission is genuine. The check is separate from marketing and is required to send through the form. You can use <Email/> instead.</p><p>Learn more at <External href="https://policies.google.com/technologies/cookies">Google’s cookie information</External>, <External href="https://privacycenter.instagram.com/policy/">Instagram’s privacy notice</External> and <External href="https://www.cloudflare.com/privacypolicy/">Cloudflare’s privacy notice</External>.</p></Part>
        <Part id="controls" title="Your browser controls"><p>Clear your WCL team and video preferences below. This affects this browser only; it does not delete messages you have sent, third-party cookies or information stored on another device.</p><Preferences/><p>Your browser’s privacy settings can remove site data, block third-party cookies or restrict storage. Blocking storage can prevent saved preferences from working; blocking external services can prevent videos, maps or security checks from loading.</p><p>For requests about information sent to WCL, see the <Link to="/privacy">Privacy Policy</Link> or contact <Email/>.</p></Part>
      </>}
      {!page?.sections?.length && kind === 'terms' && <>
        <Part id="using" title="Using the website"><p>This website provides WCL team, player, fixture, editorial and event information. You may browse and use its public features for lawful purposes. Using a separate ticketing, accreditation or other service may require additional terms displayed by that service.</p></Part>
        <Part id="content" title="Content and ownership"><p>WCL branding and website content, and the team crests, photographs, videos and other material appearing on the site, are subject to rights held by their respective owners or licensors. Their appearance does not transfer those rights to you.</p><p>You may share links to public pages. Reproduction, commercial distribution, modification or reuse of protected material requires the appropriate permission unless an applicable legal exception permits it. For permission enquiries or concerns about material on the site, contact <Email/> with the relevant page and details.</p></Part>
        <Part id="events" title="Matches, tickets and third parties"><p>Fixtures, venues, squads, start times and event arrangements can change. Check the latest event information and any confirmation from the relevant organiser or ticket seller before making travel or purchase decisions. Historical records and editorial material are not a guarantee about future participation or results.</p><p>Links to ticket sellers, broadcasters, map services and social platforms take you to services with their own terms, availability and privacy practices. A link or brand appearance is not, by itself, a promise about a current commercial relationship.</p><p>The contact form does not sell or reserve tickets and does not take payment. Purchase, admission, cancellation and refund conditions are provided by the relevant ticket seller and event organiser.</p></Part>
        <Part id="enquiries" title="Enquiries and responsible use"><p>Provide accurate contact details and only information you are entitled to share. Do not submit unlawful, abusive, deceptive or malicious material; impersonate another person; attempt to bypass security; or disrupt access for others.</p><p>A form confirmation means the email service accepted your enquiry for delivery. It is not a ticket confirmation, accreditation approval, partnership acceptance or a guarantee of a response within a particular time. If delivery cannot be confirmed, use <Email/>.</p><p>Access may be restricted where necessary to address misuse, protect the service or comply with law. Technical availability and third-party playback are not guaranteed.</p></Part>
        <Part id="rights" title="Your rights and changes"><p>Nothing in these terms is intended to remove rights or exclude responsibilities that cannot lawfully be excluded. Applicable consumer and other mandatory protections continue to apply.</p><p>These terms may be updated as the website and its services change. Review the date at the top of this page. For questions about website use, contact <Email/>. Personal information is handled as described in the <Link to="/privacy">Privacy Policy</Link>.</p></Part>
      </>}
      </article>
    </div>
  </>;
}
